---
- name: Turbonomic Webhook Actions
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: AWS - Run EC2 Playbook for Scaling
      condition: 
        event.payload.target.className == "VirtualMachine" 

      action:
        run_job_template:
          name: 'Testping'
          organization: 'Default'
          
