---
- name: Turbonomic Webhook Actions
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: AWS - Print Request Payload
      condition:
        event.payload.name == "test"

      action:
        tasks:
          - name: Print payload body
            debug:
              msg: "{{ event.payload }}"
