---
- name: Print Hello World on dynamic inventory
  become: true
  become_method: sudo
  become_user: root
  hosts: localhost


  tasks:

    - name: Wait for VMs to be reachable
      wait_for:
        host: "{{ item.ip[0] }}"
        port: 22
        delay: 5
        timeout: 60
      loop: "{{ order }}"

    - name: command module
      ansible.builtin.command: "{{ item.startcmd }}"
      delegate_to: "{{ item.ip[0] }}"
      loop: "{{ order }}"

    - name: command module for checking the status.
      ansible.builtin.command: "{{ item.statuscmd }}"
      delegate_to: "{{ item.ip[0] }}"
      loop: "{{ order }}"
      register: command_output

    - name: Print the output of command module
      ansible.builtin.debug:
        var: item.stdout
      loop: "{{ command_output.results }}"
    
      

    
    



    



