---
- name: Print Hello World on dynamic inventory
  become: true
  become_method: sudo
  become_user: root
  hosts: localhost
  tasks:
    # - name: loop through the first list
    #   debug:
    #     msg: "{{ item.stopcmd }}"
    #   loop: "{{ order }}"

    - name: command module
      ansible.builtin.command: "{{ item.stopcmd }}"
      delegate_to: 10.188.174.243

      loop: "{{ order }}"
