---
- name: Print Hello World on dynamic inventory
  become: true
  become_method: sudo
  become_user: root
  hosts: localhost
  tasks:
    # - name: loop through the first list
    #   debug:
    #     msg: "{{ item.stopcmd }}"
    #   loop: "{{ order }}"

    - name: command module
      ansible.builtin.command: 
        cmd: systemctl stop httpd
      delegate_to: "{{ item.ip[0] }}"

      loop: "{{ order }}"
