---
- name: Print Hello World on dynamic inventory
  hosts: localhost
  tasks:
    - name: Say Hello!
      debug:
        msg: "Hello World for: {{ inventory }}"

    - name: Say Hello!
      debug:
        msg: "Hello World for: {{ order }}"

    - name: Test Update Play
      debug:
        msg: "Hello from Ahmed To test the play02222"
