---
- name: Print Hello World on dynamic inventory
  become: true
  become_method: sudo
  become_user: root
  hosts: localhost
  tasks:
    - name: command module
      ansible.builtin.command: "{{ item.stopcmd }}"
      delegate_to: "{{ item.ip[0] }}"
      loop: "{{ order }}"

    - name: check status command module for checking the status.
      ansible.builtin.command: "{{ item.statuscmd }}"
      delegate_to: "{{ item.ip[0] }}"
      loop: "{{ order }}"
      register: command_output
      ignore_errors: true

    - name: print command output
      ansible.builtin.command:
        msg: "{{ command_output }}"
    # - name: Print the output of check status command module
    #   ansible.builtin.debug:
    #     msg: "STATUS: Success {{ item.item.ip[0] }}"
    #   when: "'down' in item.stdout"
    #   loop: "{{ command_output.results }}"

    # - name: Print the output of check status command module
    #   ansible.builtin.debug:
    #     msg: "STATUS: Failed to shutdown service {{ item.item.ip[0] }}"
    #   when: "'down' not in item.stdout"
    #   loop: "{{ command_output.results }}"
